spring:
  datasource:
    url: jdbc:mysql://localhost:2710/epic?serverTimezone=America/Bogota
    username: root
    password: password

debugRecipePrinting: true
doBirthdayCheck: false
doProductInventoryCheck: false
