spring:
  main:
    web-application-type: none

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/epic?serverTimezone=America/Bogota
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
